ALTER TABLE "PayrollImportBatch"
ADD COLUMN IF NOT EXISTS "importStartedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "PayrollImportBatch"
ADD COLUMN IF NOT EXISTS "importCompletedAt" TIMESTAMP;

ALTER TABLE "PayrollImportBatch"
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "PayrollImportBatch"
ADD COLUMN IF NOT EXISTS "rawPayload" JSONB;

ALTER TABLE "PayrollImportBatch"
ADD COLUMN IF NOT EXISTS "errorMessage" TEXT;

ALTER TABLE "PayrollImportBatch"
ADD COLUMN IF NOT EXISTS "totalPunches" INTEGER NOT NULL DEFAULT 0;
